@port=3000
@host=http://localhost:{{port}}

GET {{host}}/api/todo
content-type: application/json
###
GET {{host}}/api/todo?filter=ff
###
POST {{host}}/api/todo
content-type: application/json

{
"title":"abcd hello"
}
###
GET {{host}}/api/todo/26
###
DELETE {{host}}/api/todo/28
###
PATCH {{host}}/api/todo/26

{
    "title": "aaa 333"
}
###
PATCH {{host}}/api/todo/26

{
    "isDone": true
}